# Generated by Django 5.1.3 on 2024-11-28 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0003_remove_user_roles_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(max_length=400, null=True, upload_to='picture/%Y/%m/%d')),
                ('description', models.CharField(max_length=200)),
                ('comments', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('current_Assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_Assignee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=400, null=True)),
                ('picture', models.ImageField(max_length=400, null=True, upload_to='picture/%Y/%m/%d')),
                ('new_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignee', to=settings.AUTH_USER_MODEL)),
                ('previous_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignee', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytask.task')),
            ],
        ),
    ]
