# Generated by Django 5.1.3 on 2024-12-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0005_rename_current_assignee_task_current_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
